# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qrcode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for qrcode
  pod 'Firebase/Core'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
end
